random_motd_enabled: true
motds:
  - "<gradient:red:blue>Welcome to our server!</gradient>"
  - "<yellow>Have Fun!</yellow>"

random_icon_enabled: false
icons:
  - "icons/1.png"
  - "icons/2.png"

messages:
  invalid_input: "<red>Invalid input, Please use 'true' or 'false'</red>"
  setting_updated: "<green>Random MOTD feature updated to <status></green>"
  random_icon_toggle: "<green>Random icon feature is now <state></green>"